# Emerge project configuration for DMG generation
# This is configured for the emerge tool itself

[package.metadata.emerge]
# The title displayed in the application bundle and DMG
title = "Emerge Setup Tool"

# Output filename template (supports $NAME, $VERSION, $PLATFORM variables)
filename = "emerge-$PLATFORM-$VERSION"

# Directory where setup packages will be created (relative to Cargo.toml)
output-folder = "setup"

# Build commands to execute before packaging
# These run in order, and emerge will stream their output
build = [
    "cargo build --release",
]

# Files and directories to copy into the package
# Format: { "source/path" = "destination/path" }
# Paths are relative to the Cargo.toml directory for source
# Destination paths are relative to the package root:
#   - macOS DMG: Files go into the .app bundle by default
#   - Linux/Windows: Files go into the archive root directory
copy = [
    { "target/release/emerge" = "emerge" },
    { "README.md" = "README.md" },
    { "EXAMPLE.toml" = "EXAMPLE.toml" },
]

# DMG-specific configuration (macOS only)
# This section is optional - if omitted, reasonable defaults will be used
[package.metadata.emerge.dmg]
# Path to background image for the DMG window (PNG format recommended)
background = "assets/dmg-background.png"

# Position of the DMG window when opened [x, y]
window_position = [100, 100]

# Size of the DMG window [width, height]
window_size = [600, 400]

# Position of your application icon in the DMG [x, y]
app_position = [150, 200]

# Position of the Applications folder symlink [x, y]
applications_position = [450, 200]

# Optional: Additional files to include in the DMG with custom positions
# [[package.metadata.emerge.dmg.additional_files]]
# source = "docs/QuickStart.pdf"
# position = [300, 300]

